title: Researcher
url: "https://thismoots.ga"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/"
footer_text: "thismootsga"

# remote_theme: ankitsultana/researcher@gh-pages

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "resume.pdf" # put your files in the assets directory
 - name: "About"
   link: "/researcher/"
